# Generated by Django 3.1.4 on 2020-12-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='Título')),
                ('imagen', models.TextField(verbose_name='URL de imagen')),
                ('rango', models.TextField(verbose_name='Rango de la web')),
                ('popularidad', models.TextField(verbose_name='Popularidad de la web')),
                ('emision', models.TextField(verbose_name='Fecha de emisión')),
                ('episodios', models.TextField(verbose_name='Número de episodios')),
            ],
        ),
    ]
