# Generated by Django 3.1.4 on 2020-12-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='sinopsis',
            field=models.TextField(null=True, verbose_name='Sinopsis'),
        ),
    ]
