# Generated by Django 3.1.4 on 2020-12-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_anime_sinopsis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='emision',
        ),
        migrations.AddField(
            model_name='anime',
            name='fechaFinal',
            field=models.DateField(null=True, verbose_name='Fecha de Final'),
        ),
        migrations.AddField(
            model_name='anime',
            name='fechaInicio',
            field=models.DateField(null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
