# Generated by Django 3.1.4 on 2020-12-29 20:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201227_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Edad')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, verbose_name='Genero')),
                ('codigoPostal', models.CharField(max_length=8, verbose_name='Código Postal')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCalificacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Calificación')),
                ('calificacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Calificación')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.anime', verbose_name='Anime')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.informacionusuario', verbose_name='Usuario')),
            ],
        ),
    ]
